# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('use_dhcp', models.BooleanField()),
                ('ip4_address', models.CharField(max_length=16)),
                ('ip4_netmask', models.CharField(max_length=16)),
                ('ip4_gateway', models.CharField(max_length=16)),
                ('ip4_dns1', models.CharField(max_length=16)),
                ('ip4_dns2', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='WireslessNetwork',
            fields=[
                ('network_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='networkConfig.Network')),
                ('essid', models.CharField(max_length=128)),
                ('security_type', models.CharField(choices=[(b'OP', b'Open'), (b'WEP', b'WEP'), (b'WPA', b'WPA')], max_length=8)),
                ('password', models.CharField(max_length=128)),
            ],
            bases=('networkConfig.network',),
        ),
    ]
