# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='fileName',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip4_address',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip4_dns1',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip4_dns2',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip4_gateway',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip4_netmask',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='wireslessnetwork',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
