# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkConfig', '0002_auto_20160409_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
