# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkiceconfig',
            name='device',
            field=models.CharField(default='plughw:1,0', max_length=50),
            preserve_default=False,
        ),
    ]
